name: Check Tee Times

on:
  schedule:
    - cron: '*/10 * * * *' # Every 10 minutes
  workflow_dispatch: # Allows manual trigger from GitHub UI

env:
  EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
  EMAIL_RECEIVERS: ${{ secrets.EMAIL_RECEIVERS }}

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Restore the cached last_sent.txt if available
      - name: Restore last sent timestamp from cache
        uses: actions/cache@v3
        with:
          path: last_sent.txt
          key: last-sent-${{ github.run_id }}
          restore-keys: |
            last-sent-

      - name: Run tee time checker
        run: python fore_up_checker.py

      # Save last_sent.txt to cache for future runs
      - name: Save last sent timestamp to cache
        uses: actions/cache/save@v3
        with:
          path: last_sent.txt
          key: last-sent-${{ github.run_id }}
